
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const FETCH_PROFILE = "FETCHING_PROFILE";

export const FETCHING_CENTER = "FETCHING_CENTER";
export const FETCH_CENTER_DONE = "FETCH_CENTER_DONE";

export const FETCHING_CLASSROOM = "FETCHING_CLASSROOM";
export const FETCH_CLASSROOM_DONE = "FETCH_CLASSROOM_DONE";


export const FETCHING_COURSE = "FETCHING_COURSE";
export const FETCH_COURSE_DONE = "FETCH_COURSE_DONE";


export const FETCHING_CLASSES = "FETCHING_CLASSES";
export const FETCH_CLASSES_DONE = "FETCH_CLASSES_DONE";

export const FETCHING_COMMENT = "FETCHING_COMMENT";
export const FETCH_COMMENT_DONE = "FETCH_COMMENT_DONE";

export const FETCHING_CONTRACT = "FETCHING_CONTRACT";
export const FETCH_CONTRACT_DONE = "FETCH_CONTRACT_DONE";

export const FETCHING_PAYMENT = "FETCHING_PAYMENT";
export const FETCH_PAYMENT_DONE = "FETCH_PAYMENT_DONE";

export const FETCHING_REVENUE = "FETCHING_REVENUE";
export const FETCH_REVENUE_DONE = "FETCH_REVENUE_DONE";

export const FETCHING_USERS = "FETCHING_USERS";
export const FETCH_USERS_DONE = "FETCH_USERS_DONE";

export const FETCHING_STUDY = "FETCHING_STUDY";
export const FETCH_STUDY_DONE = "FETCH_STUDY_DONE";

export const FETCHING_ATTENDANT = "FETCHING_ATTENDANT";
export const FETCH_ATTENDANT_DONE = "FETCH_ATTENDANT_DONE";

export const FETCHING_SHIFT = "FETCHING_SHIFT";
export const FETCH_SHIFT_DONE = "FETCH_SHIFT_DONE";

export const FETCHING_REWARD = "FETCHING_REWARD";
export const FETCH_REWARD_DONE = "FETCH_REWARD_DONE";

export const FETCHING_STUDENT = "FETCHING_STUDENT";
export const FETCH_STUDENT_DONE = "FETCH_STUDENT_DONE";

export const FETCHING_BUSSINESSEMPLOYEE = "FETCHING_BUSSINESSEMPLOYEE";
export const FETCH_BUSSINESSEMPLOYEE_DONE = "FETCH_BUSSINESSEMPLOYEE_DONE";


export const FETCHING_MANAGERS = "FETCHING_MANAGERS";
export const FETCH_MANAGERS_DONE = "FETCH_MANAGERS_DONE";

export const FETCHING_RECEPTIONIST = "FETCHING_RECEPTIONIST";
export const FETCH_RECEPTIONIST_DONE = "FETCH_RECEPTIONIST_DONE";

export const FETCHING_STUDENTCARE = "FETCHING_STUDENTCARE";
export const FETCH_STUDENTCARE_DONE = "FETCH_STUDENTCARE_DONE";


export const FETCHING_TEACHERS = "FETCHING_TEACHERS";
export const FETCH_TEACHERS_DONE = "FETCH_TEACHERS_DONE";